#!/bin/env python
from __future__ import print_function
import os
import json
try:
    from ipalib.install import sysrestore
except:
    from ipapython import sysrestore

from ipaplatform.paths import paths

def is_ipa_installed(fstore, on_master=False):
    """
    Consider IPA client not installed if nothing is backed up
    and default.conf file does not exist. If on_master is set to True,
    the existence of default.conf file is not taken into consideration,
    since it has been already created by ipa-server-install.
    """

    client_installed = (
        fstore.has_files() or (
            not on_master and os.path.exists(paths.IPA_DEFAULT_CONF)
        )
    )

    server_installed = False
    if server_fstore.has_files() and on_master:
        server_installed = True

    return (client_installed, server_installed)


fstore = sysrestore.FileStore(paths.IPA_CLIENT_SYSRESTORE)
server_fstore = sysrestore.FileStore(paths.SYSRESTORE)

client_installed, server_installed = is_ipa_installed(fstore, on_master=True)

result = dict()
result['result'] = 'NOT_CONFIGURED'

if client_installed and server_installed:
    result['result'] = 'SERVER_CONFIGURED'
elif client_installed and not server_installed:
    result['result'] = 'CLIENT_CONFIGURED'

print(json.dumps(result))

